org.acme.rules.model.ActionDescriptor.serializer=org.acme.rules.model.ActionDescriptor.JsonFactory#serialize
org.acme.rules.model.ActionDescriptor.deserializer=org.acme.rules.model.ActionDescriptor.JsonFactory#deserialize
org.acme.rules.model.CompositeRuleDescriptor.serializer=org.acme.rules.model.CompositeRuleDescriptor.JsonFactory#serialize
org.acme.rules.model.CompositeRuleDescriptor.deserializer=org.acme.rules.model.CompositeRuleDescriptor.JsonFactory#deserialize
org.acme.rules.model.ExpressionRuleDescriptor.serializer=org.acme.rules.model.ExpressionRuleDescriptor.JsonFactory#serialize
org.acme.rules.model.ExpressionRuleDescriptor.deserializer=org.acme.rules.model.ExpressionRuleDescriptor.JsonFactory#deserialize
org.acme.rules.model.RuleDescriptor.serializer=org.acme.rules.model.RuleDescriptor.JsonFactory#serialize
org.acme.rules.model.RuleDescriptor.deserializer=org.acme.rules.model.RuleDescriptor.JsonFactory#deserialize
org.acme.rules.model.ScopedParameter.serializer=org.acme.rules.model.ScopedParameter.JsonFactory#serialize
org.acme.rules.model.ScopedParameter.deserializer=org.acme.rules.model.ScopedParameter.JsonFactory#deserialize
org.acme.rules.model.ScopedParametersDescriptor.serializer=org.acme.rules.model.ScopedParametersDescriptor.JsonFactory#serialize
org.acme.rules.model.ScopedParametersDescriptor.deserializer=org.acme.rules.model.ScopedParametersDescriptor.JsonFactory#deserialize
org.acme.rules.model.RuleTrace.serializer=org.acme.rules.model.RuleTrace.JsonFactory#serialize
org.acme.rules.model.RuleTrace.deserializer=org.acme.rules.model.RuleTrace.JsonFactory#deserialize
org.acme.rules.model.WorkflowDescriptor.serializer=org.acme.rules.model.WorkflowDescriptor.JsonFactory#serialize
org.acme.rules.model.WorkflowDescriptor.deserializer=org.acme.rules.model.WorkflowDescriptor.JsonFactory#deserialize