quarkus.http.enable-compression=true
quarkus.http.compressors=gzip,deflate,br
quarkus.jackson.serialization-inclusion=non-null
quarkus.log.level=INFO
quarkus.log.min-level=TRACE
quarkus.otel.exporter.otlp.enabled=false